# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTp-m1HzcyFlT4awROX_a3mXi2CA80cw
"""

# app.py — Streamlit application สำหรับทำนายราคาบ้าน

import streamlit as st
import numpy as np
import joblib
import json
import pandas as pd

# ===== ตั้งค่าหน้าเว็บ =====
st.set_page_config(
    page_title="ระบบทำนายราคาบ้าน",
    page_icon="🏠",
    layout="centered",
    initial_sidebar_state="expanded"
)

# ===== โหลดโมเดล =====
@st.cache_resource
def load_model():
    model = joblib.load("model_artifacts/house_price_model.pkl")
    return model

with st.spinner("กำลังโหลดโมเดล..."):
    model = load_model()

# ===== Sidebar =====
with st.sidebar:
    st.header("ℹ️ เกี่ยวกับระบบ")
    st.write("โมเดลนี้ใช้ Machine Learning ในการทำนายราคาบ้าน")

    st.divider()
    st.warning(
        "ผลลัพธ์เป็นเพียงการประมาณการ "
        "ราคาจริงอาจแตกต่างตามสภาพตลาด"
    )

# ===== Header =====
st.title("🏠 ระบบทำนายราคาบ้าน")
st.markdown("""
กรอกข้อมูลบ้านด้านล่าง ระบบจะประเมินราคาบ้านโดยใช้โมเดล Regression
""")

st.divider()

# ===== Input =====
st.subheader("📋 กรอกข้อมูลบ้าน")

col1, col2 = st.columns(2)

with col1:
    rooms = st.number_input("จำนวนห้อง", 1, 10, 3)

    distance = st.number_input(
        "ระยะห่างจากศูนย์กลางเมือง (km)",
        0.0, 50.0, 10.0
    )

    bathroom = st.number_input("จำนวนห้องน้ำ", 1, 10, 2)

    car = st.number_input("จำนวนที่จอดรถ", 0, 5, 1)

with col2:
    landsize = st.number_input(
        "ขนาดที่ดิน (ตร.ม.)",
        0.0, 10000.0, 500.0
    )

    building_area = st.number_input(
        "พื้นที่ใช้สอย (ตร.ม.)",
        0.0, 1000.0, 150.0
    )

    year_built = st.number_input(
        "ปีที่สร้าง",
        1900, 2025, 2000
    )

    region = st.selectbox(
        "โซนพื้นที่",
        ["Northern", "Southern", "Eastern", "Western"]
    )

st.divider()

# ===== Encode categorical =====
# ต้อง encode เหมือนตอน train
region_mapping = {
    "Northern": 0,
    "Southern": 1,
    "Eastern": 2,
    "Western": 3
}

region_encoded = region_mapping[region]

# ===== ปุ่ม =====
_, btn_col, _ = st.columns([1, 2, 1])
with btn_col:
    predict_button = st.button(
        "🔍 ทำนายราคา",
        use_container_width=True,
        type="primary"
    )

# ===== Prediction =====
if predict_button:

    input_data = np.array([[
        rooms, distance, bathroom, car,
        landsize, building_area, year_built,
        region_encoded
    ]])

    with st.spinner("กำลังคำนวณราคา..."):
        prediction = model.predict(input_data)[0]

    st.subheader("💰 ราคาที่คาดการณ์")

    st.success(f"""
    ### 🏷️ ราคาประมาณ: {prediction:,.0f} บาท
    """)

    # แสดงข้อมูลที่กรอก
    with st.expander("📋 ดูข้อมูลที่กรอก"):
        summary = {
            "จำนวนห้อง": rooms,
            "ระยะทาง": distance,
            "ห้องน้ำ": bathroom,
            "ที่จอดรถ": car,
            "ขนาดที่ดิน": landsize,
            "พื้นที่ใช้สอย": building_area,
            "ปีที่สร้าง": year_built,
            "โซน": region
        }

        st.dataframe(
            pd.DataFrame.from_dict(summary, orient="index", columns=["ค่า"]),
            use_container_width=True
        )