# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLljkz5vPQscKYUvTzfAHwNtdOp_8J_w
"""

import streamlit as st
import pandas as pd
import joblib
import json
import matplotlib.pyplot as plt

st.set_page_config(page_title="House Price Predictor", layout="centered")

st.title("🏠 House Price Prediction App")
st.markdown("### 🔍 กรอกข้อมูลเพื่อประเมินราคาบ้าน")
st.divider()

# -----------------------
# LOAD MODEL
# -----------------------
@st.cache_resource
def load_all():
    model = joblib.load("model_artifacts/house_price_pipeline.pkl")
    with open("model_artifacts/feature_names.json") as f:
        features = json.load(f)
    return model, features

model, feature_names = load_all()

# -----------------------
# INPUT UI (2 COLUMN)
# -----------------------
col1, col2 = st.columns(2)

with col1:
    rooms = st.slider("Rooms", 1, 10, 3)
    bedroom2 = st.slider("Bedrooms", 1, 10, 3)
    bathroom = st.slider("Bathrooms", 1, 5, 2)
    car = st.slider("Car Parking", 0, 5, 1)

with col2:
    distance = st.slider("Distance (km)", 0.0, 50.0, 10.0)
    landsize = st.number_input("Land Size (sqm)", 0.0, 1000.0, 200.0)
    buildingarea = st.number_input("Building Area (sqm)", 0.0, 500.0, 150.0)
    yearbuilt = st.slider("Year Built", 1900, 2025, 2000)

suburb = st.selectbox("Suburb", [
    "Airport West", "Altona", "Richmond", "Melbourne",
    "Brunswick", "St Kilda", "Hawthorn", "Footscray"
])

st.divider()

# -----------------------
# PREDICT
# -----------------------
if st.button("🔍 Predict Price"):

    input_dict = {feature: 0 for feature in feature_names}

    # numeric
    input_dict["Rooms"] = rooms
    input_dict["Bedroom2"] = bedroom2
    input_dict["Bathroom"] = bathroom
    input_dict["Car"] = car
    input_dict["Distance"] = distance
    input_dict["Landsize"] = landsize
    input_dict["BuildingArea"] = buildingarea
    input_dict["YearBuilt"] = yearbuilt

    # one-hot suburb (กัน error)
    suburb_key = f"Suburb_{suburb}"
    if suburb_key in input_dict:
        input_dict[suburb_key] = 1

    input_df = pd.DataFrame([input_dict])

    pred = model.predict(input_df)[0]

    # -----------------------
    # RESULT (METRIC)
    # -----------------------
    st.metric("💰 ราคาที่คาดการณ์", f"{pred:,.0f} บาท")

    # -----------------------
    # INSIGHT
    # -----------------------
    if pred > 8000000:
        st.info("🏡 บ้านระดับพรีเมียม")
    elif pred > 4000000:
        st.info("🏘️ บ้านระดับกลาง")
    else:
        st.info("🏠 บ้านราคาประหยัด")

    # -----------------------
    # GRAPH 1: Building Area
    # -----------------------
    st.subheader("📈 แนวโน้มราคาตามพื้นที่บ้าน")

    areas = list(range(50, 400, 20))
    preds = []

    for a in areas:
        temp = input_dict.copy()
        temp["BuildingArea"] = a
        df_temp = pd.DataFrame([temp])
        preds.append(model.predict(df_temp)[0])

    fig, ax = plt.subplots()
    ax.plot(areas, preds)
    ax.set_xlabel("Building Area (sqm)")
    ax.set_ylabel("Price")
    ax.set_title("Price vs Building Area")

    st.pyplot(fig)

    # -----------------------
    # GRAPH 2: Rooms
    # -----------------------
    st.subheader("📊 แนวโน้มราคาตามจำนวนห้อง")

    room_range = list(range(1, 8))
    room_prices = []

    for r in room_range:
        temp = input_dict.copy()
        temp["Rooms"] = r
        df_temp = pd.DataFrame([temp])
        room_prices.append(model.predict(df_temp)[0])

    fig2, ax2 = plt.subplots()
    ax2.plot(room_range, room_prices)
    ax2.set_xlabel("Rooms")
    ax2.set_ylabel("Price")
    ax2.set_title("Price vs Rooms")

    st.pyplot(fig2)